#!/bin/bash
set -e

# subshell so that we can export PATH without breaking other things
(
	# Both Windows to Linux and Windows to Windows CIs both start the daemon
	# through their CI script. Hence .integration-daemon-start, and 
	# .integration-daemon-stop are no-ops on these CIs.
	if [ ! "$(go env GOOS)" = 'windows' ]; then
		bundle .integration-daemon-start
	fi

	dockerPy='/docker-py'
	[ -d "$dockerPy" ] || {
		dockerPy="$DEST/docker-py"
		git clone https://github.com/docker/docker-py.git "$dockerPy"
	}

	# exporting PYTHONPATH to import "docker" from our local docker-py
	test_env PYTHONPATH="$dockerPy" py.test "$dockerPy/tests/integration"

	if [ ! "$(go env GOOS)" = 'windows' ]; then
		bundle .integration-daemon-stop
	fi
) 2>&1 | tee -a "$DEST/test.log"
